@include('web.component.header')
@include('web.component.navigation-menu')
@include('web.component.uvod-homepage')
@include('web.component.services')
@include('web.component.opening-hours')
@include('web.component.price-list')
@include('web.component.footer')
